#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_SEL4ARMVMM)  += sel4arm-vmm

sel4arm-vmm: common libsel4utils libutils libsel4 libmuslc libsel4muslcsys \
             libsel4vka libsel4twinkle libsel4vspace libsel4simple libsel4simple-default \
             libsel4platsupport libsel4platsupport libcpio libelf libsel4arm-vmm

sel4arm-vmm-components-$(CONFIG_APP_LINUX) += linux linux-dtb
sel4arm-vmm-components=$(addprefix $(STAGE_BASE)/bin/, $(sel4arm-vmm-components-y))

sel4arm-vmm: export COMPONENTS=${sel4arm-vmm-components}
sel4arm-vmm: ${sel4arm-vmm-components-y}
